<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Trail;

class WinterTrailSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $winterTrails = [
            [
                'name' => 'Dream Lake Snowshoe Trail',
                'description' => 'Magical winter wonderland snowshoe adventure to frozen Dream Lake, offering spectacular views of Hallett Peak covered in snow and ice. The trail transforms into a pristine winter landscape with snow-laden evergreens.',
                'location' => 'Estes Park, Colorado',
                'difficulty_level' => 3.0,
                'distance_km' => 3.5,
                'elevation_gain_m' => 130,
                'estimated_time_hours' => 3.5,
                'trail_type' => 'out-and-back',
                'start_coordinates' => [40.31089, -105.64450],
                'end_coordinates' => [40.31120, -105.64590],
                'route_coordinates' => [
                    [40.31089, -105.64450],
                    [40.31100, -105.64500],
                    [40.31110, -105.64550],
                    [40.31120, -105.64590]
                ],
                'status' => 'seasonal',
                'best_seasons' => ['Winter'],
                'directions' => 'From Estes Park, take Bear Lake Road. Road is plowed in winter but parking is limited.',
                'parking_info' => 'Winter parking at Bear Lake. Arrive early as spaces are limited.',
                'safety_notes' => 'Snowshoes required. Avalanche danger possible. Check conditions before going. Bring avalanche beacon in backcountry.',
                'is_featured' => true,
            ],
            [
                'name' => 'Lake Louise Frozen Waterfall Snowshoe',
                'description' => 'Stunning winter trail showcasing frozen waterfalls and the spectacular turquoise ice of Lake Louise. Walk on the frozen lake surface and admire the ice palace formations.',
                'location' => 'Lake Louise, Alberta',
                'difficulty_level' => 2.0,
                'distance_km' => 5.2,
                'elevation_gain_m' => 95,
                'estimated_time_hours' => 2.5,
                'trail_type' => 'out-and-back',
                'start_coordinates' => [51.41722, -116.21389],
                'end_coordinates' => [51.42234, -116.22567],
                'route_coordinates' => [
                    [51.41722, -116.21389],
                    [51.41900, -116.21800],
                    [51.42100, -116.22200],
                    [51.42234, -116.22567]
                ],
                'status' => 'seasonal',
                'best_seasons' => ['Winter'],
                'directions' => 'From Lake Louise village, follow signs to Chateau Lake Louise.',
                'parking_info' => 'Parking at Chateau Lake Louise. Shuttle service available in winter.',
                'safety_notes' => 'Ice conditions vary. Stay on marked trails. Beware of falling ice from cliffs.',
                'is_featured' => true,
            ],
            [
                'name' => 'Emerald Lake Cross-Country Ski Loop',
                'description' => 'Scenic Nordic skiing trail circling the frozen emerald-colored lake, surrounded by towering snow-covered peaks in Yoho National Park. Perfect for intermediate skiers.',
                'location' => 'Field, British Columbia',
                'difficulty_level' => 3.0,
                'distance_km' => 5.0,
                'elevation_gain_m' => 45,
                'estimated_time_hours' => 2.0,
                'trail_type' => 'loop',
                'start_coordinates' => [51.44333, -116.54028],
                'end_coordinates' => [51.44333, -116.54028],
                'route_coordinates' => [
                    [51.44333, -116.54028],
                    [51.44500, -116.54200],
                    [51.44600, -116.54400],
                    [51.44500, -116.54600],
                    [51.44333, -116.54028]
                ],
                'status' => 'seasonal',
                'best_seasons' => ['Winter'],
                'directions' => 'From Field, take Emerald Lake Road 9 km to parking area.',
                'parking_info' => 'Large parking area at Emerald Lake. Road is plowed in winter.',
                'safety_notes' => 'Groomed trail. Classic and skate skiing allowed. Watch for snowshoers.',
                'is_featured' => true,
            ],
            [
                'name' => 'Palisades Tahoe Cross-Country Trails',
                'description' => 'Olympic-caliber cross-country skiing facility with groomed trails for all skill levels, offering stunning Lake Tahoe views and pristine Sierra Nevada winter scenery.',
                'location' => 'Olympic Valley, California',
                'difficulty_level' => 2.0,
                'distance_km' => 8.0,
                'elevation_gain_m' => 150,
                'estimated_time_hours' => 2.5,
                'trail_type' => 'loop',
                'start_coordinates' => [39.19789, -120.23456],
                'end_coordinates' => [39.19789, -120.23456],
                'route_coordinates' => [
                    [39.19789, -120.23456],
                    [39.20000, -120.23800],
                    [39.20300, -120.24200],
                    [39.20100, -120.24600],
                    [39.19789, -120.23456]
                ],
                'status' => 'seasonal',
                'best_seasons' => ['Winter'],
                'directions' => 'From Truckee, take CA-89 south to Olympic Valley Road.',
                'parking_info' => 'Resort parking available. Trail pass required.',
                'safety_notes' => 'Groomed trails. Rentals available. Check trail conditions before going.',
                'is_featured' => false,
            ],
            [
                'name' => 'Ice Fishing at Hebgen Lake',
                'description' => 'Premier ice fishing destination offering excellent trout fishing opportunities on a frozen mountain reservoir. Access multiple fishing spots across the expansive frozen lake.',
                'location' => 'West Yellowstone, Montana',
                'difficulty_level' => 2.0,
                'distance_km' => 2.0,
                'elevation_gain_m' => 10,
                'estimated_time_hours' => 4.0,
                'trail_type' => 'out-and-back',
                'start_coordinates' => [44.85234, -111.35678],
                'end_coordinates' => [44.86456, -111.36789],
                'route_coordinates' => [
                    [44.85234, -111.35678],
                    [44.85800, -111.36000],
                    [44.86200, -111.36400],
                    [44.86456, -111.36789]
                ],
                'status' => 'seasonal',
                'best_seasons' => ['Winter'],
                'directions' => 'From West Yellowstone, take US-287 north 5 miles to Hebgen Lake access.',
                'parking_info' => 'Plowed parking areas at lake access points.',
                'safety_notes' => 'Check ice thickness before venturing out. Minimum 4 inches for walking. Bring safety equipment.',
                'is_featured' => false,
            ],
            [
                'name' => 'Vail Back Bowls Backcountry Skiing',
                'description' => 'World-renowned powder skiing in Vail\'s legendary back bowls, offering expansive terrain for advanced skiers seeking untouched snow and challenging descents.',
                'location' => 'Vail, Colorado',
                'difficulty_level' => 5.0,
                'distance_km' => 6.5,
                'elevation_gain_m' => 450,
                'estimated_time_hours' => 5.0,
                'trail_type' => 'point-to-point',
                'start_coordinates' => [39.64023, -106.35456],
                'end_coordinates' => [39.62789, -106.33234],
                'route_coordinates' => [
                    [39.64023, -106.35456],
                    [39.63500, -106.34800],
                    [39.63000, -106.34200],
                    [39.62789, -106.33234]
                ],
                'status' => 'seasonal',
                'best_seasons' => ['Winter'],
                'directions' => 'Access via Vail Resort gondola. Resort ticket required.',
                'parking_info' => 'Vail Village parking structures. Arrive early during peak season.',
                'safety_notes' => 'Expert terrain only. Avalanche gear required. Check avalanche forecast daily.',
                'is_featured' => true,
            ],
            [
                'name' => 'Jenny Lake Snowshoe Circuit',
                'description' => 'Peaceful winter snowshoe around the frozen shores of iconic Jenny Lake with stunning views of the snow-covered Teton Range reflecting in patches of ice.',
                'location' => 'Moose, Wyoming',
                'difficulty_level' => 3.0,
                'distance_km' => 11.3,
                'elevation_gain_m' => 120,
                'estimated_time_hours' => 4.5,
                'trail_type' => 'loop',
                'start_coordinates' => [43.75234, -110.72456],
                'end_coordinates' => [43.75234, -110.72456],
                'route_coordinates' => [
                    [43.75234, -110.72456],
                    [43.75800, -110.72800],
                    [43.76200, -110.73200],
                    [43.75800, -110.73600],
                    [43.75234, -110.72456]
                ],
                'status' => 'seasonal',
                'best_seasons' => ['Winter'],
                'directions' => 'From Moose, take Teton Park Road north to Jenny Lake area.',
                'parking_info' => 'Winter parking at Taggart Lake trailhead. Road not plowed to Jenny Lake.',
                'safety_notes' => 'Snowshoes essential. Wildlife active. Carry bear spray even in winter.',
                'is_featured' => true,
            ],
            [
                'name' => 'Breckenridge Nordic Center Trails',
                'description' => 'Extensive groomed cross-country ski trail network through aspen groves and meadows, offering trails for all abilities with spectacular mountain vistas.',
                'location' => 'Breckenridge, Colorado',
                'difficulty_level' => 2.0,
                'distance_km' => 12.0,
                'elevation_gain_m' => 180,
                'estimated_time_hours' => 3.0,
                'trail_type' => 'loop',
                'start_coordinates' => [39.48123, -106.04567],
                'end_coordinates' => [39.48123, -106.04567],
                'route_coordinates' => [
                    [39.48123, -106.04567],
                    [39.48500, -106.05000],
                    [39.49000, -106.05500],
                    [39.48800, -106.06000],
                    [39.48123, -106.04567]
                ],
                'status' => 'seasonal',
                'best_seasons' => ['Winter'],
                'directions' => 'From Breckenridge, take Ski Hill Road to Nordic Center.',
                'parking_info' => 'Nordic Center parking. Trail pass required.',
                'safety_notes' => 'Groomed trails. Equipment rentals and lessons available.',
                'is_featured' => false,
            ],
            [
                'name' => 'Lake Minnewanka Ice Fishing Trail',
                'description' => 'Popular ice fishing destination in Banff National Park, where anglers can catch lake trout through the ice while surrounded by spectacular mountain scenery.',
                'location' => 'Banff, Alberta',
                'difficulty_level' => 2.0,
                'distance_km' => 1.5,
                'elevation_gain_m' => 5,
                'estimated_time_hours' => 3.5,
                'trail_type' => 'out-and-back',
                'start_coordinates' => [51.24567, -115.50234],
                'end_coordinates' => [51.25789, -115.51456],
                'route_coordinates' => [
                    [51.24567, -115.50234],
                    [51.25100, -115.50700],
                    [51.25500, -115.51100],
                    [51.25789, -115.51456]
                ],
                'status' => 'seasonal',
                'best_seasons' => ['Winter'],
                'directions' => 'From Banff townsite, take Lake Minnewanka Road 5 km to parking.',
                'parking_info' => 'Plowed parking at lake access. National park pass required.',
                'safety_notes' => 'Check ice conditions with Parks Canada. Minimum safe ice thickness is 4 inches.',
                'is_featured' => false,
            ],
            [
                'name' => 'Alta Ski Area Backcountry Access',
                'description' => 'Gateway to Utah\'s legendary powder skiing, accessing high-alpine bowls and couloirs for expert skiers seeking the deepest snow in North America.',
                'location' => 'Alta, Utah',
                'difficulty_level' => 5.0,
                'distance_km' => 8.0,
                'elevation_gain_m' => 520,
                'estimated_time_hours' => 6.0,
                'trail_type' => 'out-and-back',
                'start_coordinates' => [40.58789, -111.63567],
                'end_coordinates' => [40.59567, -111.65234],
                'route_coordinates' => [
                    [40.58789, -111.63567],
                    [40.59100, -111.64000],
                    [40.59300, -111.64600],
                    [40.59567, -111.65234]
                ],
                'status' => 'seasonal',
                'best_seasons' => ['Winter'],
                'directions' => 'From Salt Lake City, take I-215 to UT-190 east to Alta.',
                'parking_info' => 'Resort parking. Access requires ski pass or backcountry permit.',
                'safety_notes' => 'EXPERT ONLY. Avalanche beacon, probe, and shovel mandatory. Check UAC avalanche forecast.',
                'is_featured' => true,
            ],
            [
                'name' => 'Yellowstone Winter Wildlife Snowshoe',
                'description' => 'Spectacular winter wildlife viewing snowshoe trail through Yellowstone\'s thermal areas, where bison, elk, and other animals gather near warm geothermal features.',
                'location' => 'Gardiner, Montana',
                'difficulty_level' => 2.0,
                'distance_km' => 6.4,
                'elevation_gain_m' => 75,
                'estimated_time_hours' => 3.0,
                'trail_type' => 'out-and-back',
                'start_coordinates' => [44.97234, -110.70567],
                'end_coordinates' => [44.98456, -110.71789],
                'route_coordinates' => [
                    [44.97234, -110.70567],
                    [44.97600, -110.71000],
                    [44.98100, -110.71400],
                    [44.98456, -110.71789]
                ],
                'status' => 'seasonal',
                'best_seasons' => ['Winter'],
                'directions' => 'From Gardiner, enter Yellowstone via North Entrance.',
                'parking_info' => 'Mammoth Hot Springs parking area.',
                'safety_notes' => 'Stay on boardwalks near thermal features. Give wildlife 25+ yards space.',
                'is_featured' => false,
            ],
            [
                'name' => 'Cascade Canyon Snowshoe Adventure',
                'description' => 'Grand Teton winter classic offering incredible solitude and dramatic canyon views, with opportunities to spot moose, bighorn sheep, and other winter wildlife.',
                'location' => 'Moose, Wyoming',
                'difficulty_level' => 4.0,
                'distance_km' => 15.3,
                'elevation_gain_m' => 275,
                'estimated_time_hours' => 7.0,
                'trail_type' => 'out-and-back',
                'start_coordinates' => [43.75234, -110.72456],
                'end_coordinates' => [43.77789, -110.78567],
                'route_coordinates' => [
                    [43.75234, -110.72456],
                    [43.76000, -110.74000],
                    [43.76800, -110.76000],
                    [43.77500, -110.77500],
                    [43.77789, -110.78567]
                ],
                'status' => 'seasonal',
                'best_seasons' => ['Winter'],
                'directions' => 'From Moose Visitor Center, snowshoe or ski to Jenny Lake, then up Cascade Canyon.',
                'parking_info' => 'Park at Taggart Lake trailhead. Road not plowed beyond.',
                'safety_notes' => 'Long winter day trip. Start early. Avalanche danger in canyon. Carry beacon.',
                'is_featured' => false,
            ],
            [
                'name' => 'Jackson Hole Backcountry Powder Run',
                'description' => 'Epic expert-only skiing accessing Jackson Hole\'s famous steep terrain and deep powder stashes, including the legendary Corbet\'s Couloir area.',
                'location' => 'Teton Village, Wyoming',
                'difficulty_level' => 5.0,
                'distance_km' => 5.8,
                'elevation_gain_m' => 480,
                'estimated_time_hours' => 4.5,
                'trail_type' => 'point-to-point',
                'start_coordinates' => [43.58789, -110.82567],
                'end_coordinates' => [43.57234, -110.81123],
                'route_coordinates' => [
                    [43.58789, -110.82567],
                    [43.58300, -110.82200],
                    [43.57800, -110.81800],
                    [43.57234, -110.81123]
                ],
                'status' => 'seasonal',
                'best_seasons' => ['Winter'],
                'directions' => 'Access via Jackson Hole tram to 10,450 ft summit.',
                'parking_info' => 'Teton Village parking. Resort pass required.',
                'safety_notes' => 'EXTREME EXPERT TERRAIN. Avalanche gear mandatory. Partner required.',
                'is_featured' => true,
            ],
            [
                'name' => 'Maroon Bells Snowshoe Loop',
                'description' => 'Colorado\'s most photographed peaks covered in winter splendor, offering a moderate snowshoe adventure through pristine aspen groves with iconic mountain reflections.',
                'location' => 'Aspen, Colorado',
                'difficulty_level' => 3.0,
                'distance_km' => 7.2,
                'elevation_gain_m' => 145,
                'estimated_time_hours' => 3.5,
                'trail_type' => 'loop',
                'start_coordinates' => [39.09123, -106.94567],
                'end_coordinates' => [39.09123, -106.94567],
                'route_coordinates' => [
                    [39.09123, -106.94567],
                    [39.09500, -106.95000],
                    [39.09800, -106.95500],
                    [39.09600, -106.96000],
                    [39.09123, -106.94567]
                ],
                'status' => 'seasonal',
                'best_seasons' => ['Winter'],
                'directions' => 'From Aspen, take Maroon Creek Road. Road closed in winter - use shuttle or snowmobile.',
                'parking_info' => 'Park in Aspen and take snowcat shuttle (reservation required).',
                'safety_notes' => 'Avalanche terrain. Check forecast. Popular area but still backcountry.',
                'is_featured' => true,
            ],
            [
                'name' => 'Royal Gorge Cross-Country Ski Trails',
                'description' => 'North America\'s largest cross-country ski resort featuring 140 trails across 6,000 acres of groomed terrain through Sierra Nevada forests.',
                'location' => 'Soda Springs, California',
                'difficulty_level' => 2.0,
                'distance_km' => 10.0,
                'elevation_gain_m' => 160,
                'estimated_time_hours' => 3.0,
                'trail_type' => 'loop',
                'start_coordinates' => [39.31234, -120.36789],
                'end_coordinates' => [39.31234, -120.36789],
                'route_coordinates' => [
                    [39.31234, -120.36789],
                    [39.31800, -120.37200],
                    [39.32300, -120.37800],
                    [39.32100, -120.38400],
                    [39.31234, -120.36789]
                ],
                'status' => 'seasonal',
                'best_seasons' => ['Winter'],
                'directions' => 'From Truckee, take I-80 west to Soda Springs exit.',
                'parking_info' => 'Large resort parking. Trail pass required.',
                'safety_notes' => 'Well-maintained trails. Full service resort with rentals and lessons.',
                'is_featured' => false,
            ],
        ];

        foreach ($winterTrails as $trail) {
            Trail::create($trail);
        }
    }
}